TDMUCLASS-master/TDMUCLASS/Controllers/TDMUCLASSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TDMUCLASS.Models;

namespace TDMUCLASS.Controllers
{
    public class TDMUCLASSController : Controller
    {
        private string connection;
        private dbTDMUCLASSDataContext db;

        public TDMUCLASSController()
        {
            // Khởi tạo chuỗi kết nối
            db = Connect.GetConnect();
        }



        // GET: TDMUCLASS

        public ActionResult NavPartial()
        {
            return PartialView();
        }
        public ActionResult NavPartialUserSV()
        {
            return PartialView();
        }
        public ActionResult NavPartialUserGV()
        {
            return PartialView();
        }
        public ActionResult NavPartialUserNV()
        {
            return PartialView();
        }
        public ActionResult ChaoMungPartial()
        {
            return PartialView();
        }
        public ActionResult HeaderPartial()
        {
            return PartialView();
        }
        public ActionResult GioiThieuPartial()
        {
            return PartialView();
        }
        public ActionResult DatPhongPartial()
        {
            var viewModel = new DayHocPhongHoc
            {
                DayHocData = db.DAYHOCs.ToList(),
                PhongHocData = db.PHONGHOCs.ToList()
            };

            return PartialView(viewModel); 
        }


        public ActionResult CategoryPartial()
        {
            return PartialView();
        }
        public ActionResult AboutPartial()
        {
            return PartialView();
        }
        public ActionResult Home()
        {    
            return View();
        }
        public ActionResult FooterPartial()
        {
            return PartialView();
        }
        public ActionResult FooterPartialUser()
        {
            return PartialView();
        }
        [HttpPost]
        public ActionResult GuiPhanHoi(string phanhoi, string email)
        {
            // Validate and save the feedback and email to the database
            if (!string.IsNullOrEmpty(phanhoi) && !string.IsNullOrEmpty(email))
            {
                var phanhoiEntity = new PHANHOI
                {
                    NoiDung = phanhoi,
                    Email = email,
                    NgayGui = DateTime.Now // You may need to adjust this based on your database schema
                };

                db.PHANHOIs.InsertOnSubmit(phanhoiEntity);
                db.SubmitChanges(); // Save changes to the database

                // Optionally, you can redirect the user to a success page or perform other actions
                return RedirectToAction("Home");
            }

            // If validation fails, you may want to handle the error accordingly
            return RedirectToAction("Error");
        }


        private List<TINTUC> LayTinMoi(int count)
        {
            return db.TINTUCs.OrderByDescending(a => a.NgayDang).Take(count).ToList();
        }
        public ActionResult TinTucPartial()
        {
            var listTinMoi = LayTinMoi(8);
            return PartialView(listTinMoi);
        }
        public ActionResult test ()
        {
            return View();
        }
    }
}

TDMUCLASS-master/TDMUCLASS/Views/Shared/CategoryPartial.cshtml
        <!-- Category Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center mx-auto mb-5 wow fadeInUp" data-wow-delay="0.1s" style="max-width: 600px;">
            <h1 class="mb-3">Property Types</h1>
            <p>Eirmod sed ipsum dolor sit rebum labore magna erat. Tempor ut dolore lorem kasd vero ipsum sit eirmod sit. Ipsum diam justo sed rebum vero dolor duo.</p>
        </div>
        <div class="row g-4">
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-apartment.png" alt="Icon">
                        </div>
                        <h6>Apartment</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-villa.png" alt="Icon">
                        </div>
                        <h6>Villa</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-house.png" alt="Icon">
                        </div>
                        <h6>Home</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.7s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-housing.png" alt="Icon">
                        </div>
                        <h6>Office</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.1s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-building.png" alt="Icon">
                        </div>
                        <h6>Building</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.3s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-neighborhood.png" alt="Icon">
                        </div>
                        <h6>Townhouse</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
            <div class="col-lg-3 col-sm-6 wow fadeInUp" data-wow-delay="0.5s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-condominium.png" alt="Icon">
                        </div>
                        <h6>Shop</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>

            <div class="    " data-wow-delay="0.7s">
                <a class="cat-item d-block bg-light text-center rounded p-3" href="">
                    <div class="rounded p-4">
                        <div class="icon mb-3">
                            <img class="img-fluid" src="~/img/icon-luxury.png" alt="Icon">
                        </div>
                        <h6>Garage</h6>
                        <span>123 Properties</span>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>
<!-- Category End -->

TDMUCLASS-master/TDMUCLASS/Views/Shared/FooterPartial.cshtml
        <!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <img style="width:250px; height: 80px;padding-bottom: 30px;" src="~/img/logo-nav .png" />
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Số 06, Trần Văn Ơn, Phú Hòa, Thủ Dầu Một, Bình Dương</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>0274-383-4512 | 0274-382-2518 | 0274-384-4226</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/dhtdm2009"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href="https://www.youtube.com/channel/UCBtKDWV4vp7QPl8474svFWw"><i class="fab fa-youtube"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">ĐƯỜNG DẪN</h5>
                <a class="btn btn-link text-white-50" href="#">Trang chủ</a>
                <a class="btn btn-link text-white-50" href="#gioithieu">Giới thiệu</a>
                <a class="btn btn-link text-white-50" href="#tintuc">Tin Tức</a>
                <a class="btn btn-link text-white-50" href="~/Account/Login">Thời khóa biểu</a>
                <a class="btn btn-link text-white-50" href="~/Account/Login">Đăng nhập</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">HÌNH ẢNH</h5>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header3.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/tin3.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header4.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/tin5.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header1.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header2.jpg" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Phản hồi hệ thống</h5>
                <form action="@Url.Action("GuiPhanHoi", "TDMUCLASS")" method="post">
                    <div class="position-relative mx-auto" style="max-width: 400px; padding:5px 0px;">
                        <input class="form-control bg-transparent w-1000 py-3 ps-4 pe-5" name="phanhoi" type="text" placeholder="Nội dung phản hồi" required>
                    </div>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" name="email" type="email" placeholder="Your email" required>
                        <button type="submit" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Gửi</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">TDMUCLASS</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom text-uppercase" href="#">Phan Ngọc Tùng</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

TDMUCLASS-master/TDMUCLASS/Views/Shared/FooterPartialUser.cshtml
<!-- Footer Start -->
<div class="container-fluid bg-dark text-white-50 footer pt-5 mt-5 wow fadeIn" data-wow-delay="0.1s">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <img style="width:270px; height: 100px;padding-bottom: 30px;" src="~/img/logo-nav .png" />
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>Số 06, Trần Văn Ơn, Phú Hòa, Thủ Dầu Một, Bình Dương</p>
                <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>0274-383-4512 | 0274-382-2518 | 0274-384-4226</p>
                <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href="https://www.facebook.com/dhtdm2009"><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href="https://www.youtube.com/channel/UCBtKDWV4vp7QPl8474svFWw"><i class="fab fa-youtube"></i></a>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">ĐƯỜNG DẪN</h5>
                <a class="btn btn-link text-white-50" href="#">Trang chủ</a>
                <a class="btn btn-link text-white-50" href="~/Account/DatPhong">Đặt phòng</a>
                <a class="btn btn-link text-white-50" href="~/Account/BaoCaoSuCo">Báo cáo sự cố</a>
                <a class="btn btn-link text-white-50" href="@Url.Action("Logout", "Account")">Đăng xuất</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">HÌNH ẢNH</h5>
                <div class="row g-2 pt-2">
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header3.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/tin3.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header4.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/tin5.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header1.jpg" alt="">
                    </div>
                    <div class="col-4">
                        <img class="img-fluid rounded bg-light p-1" src="~/img/header2.jpg" alt="">
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-6">
                <h5 class="text-white mb-4">Phản hồi hệ thống</h5>
                <form action="@Url.Action("GuiPhanHoi", "TDMUCLASS")" method="post">
                    <div class="position-relative mx-auto" style="max-width: 400px; padding:5px 0px;">
                        <input class="form-control bg-transparent w-1000 py-3 ps-4 pe-5" name="phanhoi" type="text" placeholder="Nội dung phản hồi" required>
                    </div>
                    <div class="position-relative mx-auto" style="max-width: 400px;">
                        <input class="form-control bg-transparent w-100 py-3 ps-4 pe-5" name="email" type="email" placeholder="Your email" required>
                        <button type="submit" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">Gửi</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    &copy; <a class="border-bottom" href="#">TDMUCLASS</a>, All Right Reserved.

                    <!--/*** This template is free as long as you keep the footer author’s credit link/attribution link/backlink. If you'd like to use the template without the footer author’s credit link/attribution link/backlink, you can purchase the Credit Removal License from "https://htmlcodex.com/credit-removal". Thank you for your support. ***/-->
                    Designed By <a class="border-bottom text-uppercase" href="#">VO THANH LOC VIP NGOO</a>
                </div>
                <div class="col-md-6 text-center text-md-end">
                    <div class="footer-menu">
                        <a href="">Home</a>
                        <a href="">Cookies</a>
                        <a href="">Help</a>
                        <a href="">FQAs</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

TDMUCLASS-master/TDMUCLASS/Views/Shared/_LayoutNhanVien.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Favicons -->
    <link href="~/~/assetsAdminAdmin/img/favicon.png" rel="icon">
    <link href="~/assetsAdmin/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link href="https://fonts.gstatic.com" rel="preconnect">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/assetsAdmin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assetsAdmin/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/assetsAdmin/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
    <link href="~/assetsAdmin/vendor/quill/quill.snow.css" rel="stylesheet">
    <link href="~/assetsAdmin/vendor/quill/quill.bubble.css" rel="stylesheet">
    <link href="~/assetsAdmin/vendor/remixicon/remixicon.css" rel="stylesheet">
    <link href="~/assetsAdmin/vendor/simple-datatables/style.css" rel="stylesheet">
    <style>

        .thongbao {
            position: fixed;
            width: 450px;
            display: flex;
            justify-content: center;
            align-items: center;
            z-index: 100;
            border: hidden;
            top: 10%;
            left: 50%;
            transform: translateX(-50%);
            text-align: center;
        }
    </style>

    <!-- Template Main CSS File -->
    <link href="~/assetsAdmin/css/style.css" rel="stylesheet">
</head>
<body>
    <div>
        @Html.Action("NavPartialUserNV", "TDMUCLASS")
        <!-- Body -->
        @RenderBody()


    </div>

    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="~/assetsAdmin/vendor/apexcharts/apexcharts.min.js"></script>
    <script src="~/assetsAdmin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/assetsAdmin/vendor/chart.js/chart.umd.js"></script>
    <script src="~/assetsAdmin/vendor/echarts/echarts.min.js"></script>
    <script src="~/assetsAdmin/vendor/quill/quill.min.js"></script>
    <script src="~/assetsAdmin/vendor/simple-datatables/simple-datatables.js"></script>
    <script src="~/assetsAdmin/vendor/tinymce/tinymce.min.js"></script>
    <script src="~/assetsAdmin/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/assetsAdmin/js/main.js"></script>

</body>
</html>

TDMUCLASS-master/TDMUCLASS/Views/Shared/_LayoutShared.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
</body>
</html>

TDMUCLASS-master/TDMUCLASS/Views/Shared/_LayoutTeacher.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <style>
        .thongbao-container {
            position: relative;
        }

        .thongbao {
            padding-top: 10px;
            text-align: center;
            z-index: 100;
            border: hidden;
            width: 350px;
            position: absolute;
            top: 0;
            left: 50%;
            transform: translateX(-50%);
        }
    </style>
</head>


<body>
    <div class="container-xxl bg-white p-0">
        <!-- Nav -->
        @Html.Action("NavPartialUserGV", "TDMUCLASS")
        <!-- ChaoMung -->
        <div class="thongbao-container">
            <!-- Body -->
            @RenderBody()
            <div id="thongbao" class="alert alert-success thongbao" style="display: none;">
                <i class="fa-solid fa-check fa-2xl" style="color: #00e61b;"></i> <br /> Đã xử lý thành công. <br />Vui lòng kiểm tra tình trạng trong lịch sử!
            </div>
        </div>


        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    <!-- Footer -->
    @Html.Action("FooterPartialUser", "TDMUCLASS")



    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
</body>
</html>
<script>
    function tailai() {
        location.reload();
    }
</script>

TDMUCLASS-master/TDMUCLASS/Views/Shared/_LayoutUser.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <!-- Favicon -->
    <link href="~/img/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Heebo:wght@400;500;600&family=Inter:wght@700;800&display=swap" rel="stylesheet">

    <!-- Icon Font Stylesheet -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">

    <!-- Template Stylesheet -->
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/styleTinTuc.css" rel="stylesheet" />
</head>


<body>
    <div class="container-xxl bg-white p-0">
        <!-- Nav -->
        @Html.Action("NavPartial", "TDMUCLASS")

        <!-- Header -->
        @Html.Action("HeaderPartial", "TDMUCLASS")

        <!-- GioiThieu -->
        @Html.Action("GioiThieuPartial", "TDMUCLASS")
        
        <!-- TinTuc -->
        @Html.Action("TinTucPartial", "TDMUCLASS")

        <!-- About -->
        @Html.Action("AboutPartial", "TDMUCLASS")

        <!-- Body -->
        @RenderBody()

        <!-- Back to Top -->
        <a href="#" class="btn btn-lg btn-primary btn-lg-square back-to-top"><i class="bi bi-arrow-up"></i></a>
    </div>
    <!-- Footer -->
    @Html.Action("FooterPartial", "TDMUCLASS")


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/owlcarousel/owl.carousel.min.js"></script>

    <!-- Template Javascript -->
    <script src="~/js/main.js"></script>
</body>
</html>
<script>
    function tailai() {
        location.reload();
    }
</script>